{% set version = '0.2.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cubist
  version: {{ version|replace("-", "_") }}

source:
  fn: Cubist_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Cubist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Cubist/Cubist_{{ version }}.tar.gz
  sha256: cd3e152cc72ab33f720a8fb6b8b6787171e1c037cfda48f1735ab692ed6d85d4

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-lattice
    - r-reshape2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-lattice
    - r-reshape2

test:
  commands:
    - $R -e "library('Cubist')"           # [not win]
    - "\"%R%\" -e \"library('Cubist')\""  # [win]

about:
  home: https://topepo.github.io/Cubist
  license: GPL-3
  summary: Regression modeling using rules with added instance-based corrections.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
