travis:
  secure:
    BINSTAR_TOKEN: ZnNVy6F8Ctsi9bnekXZd1v0z4PY1hcqgQSUOB3mQHxC+QQwR2zyBdcpMC+E5RiCrG66tBF1eK/sSUFrP3DfyEBhk6F6NTgawRNh+T72XgvgaiV3vQy3FSjCL3mrDVuBi9PRt0KMcj4xONMZlOEd9jK3BiEhtXkmDcY6LfkkhDC/EPr1g8YfCMfpmDbDnpDwGIBe7UT0EeS/aBW0KfwPlMDD0n997Z6pyyHAumBNyjGG2e1iBKCl41WkSLrHK+XdlzqWbyFCVth3MYUz83HhIX3MP49/mUbiINOy0KHgK00igmOlEg36QeTUg3tanhgWy5yU0EFOGhy+oXA1trZjgBU8tKPxCBwT27LB/pt3A2w/Ysf3zAMmqKlHg0Gg6fDzqzA2uZA6tpkdmAiAlSWU+SDBykeVn9dnaEVHPNjxUYfxp+C/iyJzxlQJUTwfMLrQsvaus952TAez4Se9vxPDjvW+uEpLMIqOR25Wk49gL6pFPIy40DqiEC8X46mXCB9F+bcZ/qadclSVC9sUXfdPv8hVns8Y9ZfWdbJ9vnoVgyOxHx0mM4ljnpUFsNJKKDhfav4d0ds+WK+I1dB50m3IGSE8XL2nqNq43toS6zFlWrW1/YhS5BZPfd1UnFsVfeAiNPVM6Q0b2P53X9ZArXgE4p18uj/lekzxRVAbl3Y6KrRI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
